### ISSUE TITLE
pip install -r requirement.txt can't work

### ISSUE THREAD

**Issue by sillygod** [kenttw/bitcoin-zoo#1]
### 部份套件安裝會有問題
1. rest_framework_swagger==0.2.1套件應該改成 django-rest-swagger==0.2.6，因為前者抓不到，無法下1載
2. MySQL-python 這套件會有問題，錯誤訊息如下
   InstallationError: Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_hanzawa/MySQL-python

**Comment by kenttw** [comment]
1. Ans : ok go it , i will fix it 
2. Ans : because this MySQL-python package need MySQL Dev library , you can refer http://mysql-python.blogspot.no/2012/11/is-mysqldb-hard-to-install.html . You can run command line as below
   # apt-get install build-essential python-dev libmysqlclient-dev

**Comment by sillygod** [comment]
我把**requirements.txt**修改過了喔

**Comment by kenttw** [comment]
ok i got thx
